Repository woowa-techcamp-2020/hkb-2, pull requests merged in 2020-08, with the labels that each got.

#51 Client/49 GitHub login
  client/src/api/apiRoutes.ts
  client/src/api/user.ts
  client/src/components/Login/Login.ts
  server/package-lock.json
  server/package.json
  server/src/api/user.ts
  server/src/passport.ts
  server/src/repository/user-repository.ts
  server/src/routes/user-routes.ts
  server/src/utils/fetch-wrapper.ts
Labels: api, backend, frontend

#53 Feat/52 category fetch
  client/src/api/apiRoutes.ts
  client/src/api/category.ts
  client/src/components/AddNewTransaction/AddNewTransaction.scss
  client/src/components/AddNewTransaction/AddNewTransaction.test.ts
  client/src/components/AddNewTransaction/AddNewTransaction.ts
  client/src/components/AddNewTransaction/index.ts
  client/src/components/App/App.ts
  client/src/components/BoxInput/BoxInput.ts
  client/src/components/Button/Button.ts
  client/src/components/Header/Header.ts
  client/src/components/TransactionItem/TransactionItem.ts
  client/src/components/TransactionList/TransactionList.ts
  client/src/pages/History/History.scss
  client/src/pages/History/History.ts
  client/src/pages/History/index.ts
  client/src/utils/wooact/Component.ts
  client/src/utils/wooact/Diffing.ts
  client/src/utils/wooact/createElement.ts
  client/src/utils/wooact/defaultElements.ts
  server/src/repository/category-repository.ts
  server/src/routes/__test__/category-routes.test.ts
  server/src/routes/category-routes.ts
  server/src/routes/index.ts
  server/src/routes/transaction-routes.ts
  server/src/service/category-service.ts
  server/src/service/user-service.ts
Labels: api, backend, component, db, frontend

#55 githubCallback 함수 리팩토링
  server/src/passport.ts
Labels: api, backend, refactoring

#57 Feat/26 store design
  client/src/api/transaction.ts
  client/src/components/AddNewTransaction/AddNewTransaction.scss
  client/src/components/AddNewTransaction/AddNewTransaction.ts
  client/src/components/App/App.scss
  client/src/components/BoxInput/BoxInput.scss
  client/src/components/BoxInput/BoxInput.ts
  client/src/components/Button/Button.ts
  client/src/components/Header/Header.ts
  client/src/components/Signup/Signup.ts
  client/src/components/TransactionItem/TransactionItem.scss
  client/src/components/TransactionItem/TransactionItem.ts
  client/src/components/TransactionList/TransactionList.scss
  client/src/components/TransactionList/TransactionList.ts
  client/src/index.ts
  client/src/modules/Store.ts
  client/src/modules/TransactionStore.ts
  client/src/pages/History/History.ts
  client/src/styles/_normalize.scss
  client/src/styles/_variables.scss
  client/src/utils/connectStore.ts
  client/src/utils/wooact/Component.ts
  client/src/utils/wooact/createElement.ts
  client/src/utils/wooact/eventHandler.ts
  server/src/repository/transaction-repository.ts
  server/src/service/transaction-service.ts
Labels: frontend

#59 Feat/56 routing
  client/src/components/App/App.ts
  client/src/components/Header/Header.ts
  client/src/index.ts
  client/src/pages/Calendar/Calendar.scss
  client/src/pages/Calendar/Calendar.ts
  client/src/pages/Calendar/index.ts
  client/src/pages/History/index.ts
  client/src/pages/SignIn/SignIn.scss
  client/src/pages/SignIn/SignIn.ts
  client/src/pages/SignIn/index.ts
  client/src/pages/Statistics/Statistics.scss
  client/src/pages/Statistics/Statistics.ts
  client/src/pages/Statistics/index.ts
  client/src/pages/Transaction/Transaction.scss
  client/src/pages/Transaction/Transaction.ts
  client/src/pages/Transaction/index.ts
  client/src/utils/Routing.ts
  server/src/repository/transaction-repository.ts
Labels: frontend

#71 Feat/70 visibility filter
  client/src/components/AddNewTransaction/AddNewTransaction.scss
  client/src/components/App/App.scss
  client/src/components/App/App.ts
  client/src/components/Header/Header.scss
  client/src/components/Header/Header.ts
  client/src/components/SideBar/SideBar.scss
  client/src/components/SideBar/SideBar.ts
  client/src/components/TransactionItem/TransactionItem.ts
  client/src/components/TransactionList/TransactionList.ts
  client/src/modules/TransactionStore.ts
  client/src/modules/VisibleStore.ts
  client/src/modules/index.ts
  client/src/pages/Calendar/Calendar.scss
  client/src/pages/Calendar/Calendar.ts
  client/src/pages/Statistics/Statistics.ts
  client/src/pages/Transaction/Transaction.ts
  client/src/utils/Routing.ts
  client/src/utils/dateInfos.ts
Labels: frontend

#73 Feat/78 transaction api
  client/src/api/transaction.ts
  server/src/repository/transaction-repository.ts
  server/src/routes/transaction-routes.ts
  server/src/service/transaction-service.ts
  server/src/utils/query-executor.ts
Labels: api, backend, frontend

#77 Bug/76 after routing not working
  client/src/components/App/App.scss
  client/src/components/App/App.ts
  client/src/components/CalendarItem/CalendarItem.scss
  client/src/components/CalendarItem/CalendarItem.ts
  client/src/components/SideBar/SideBar.ts
  client/src/components/TransactionList/TransactionList.ts
  client/src/modules/DateStore.ts
  client/src/modules/index.ts
  client/src/pages/Calendar/Calendar.scss
  client/src/pages/Calendar/Calendar.ts
  client/src/pages/Router.ts
  client/src/pages/Statistics/Statistics.ts
  client/src/pages/Transaction/Transaction.ts
  client/src/utils/Routing.ts
  client/src/utils/dateInfos.ts
Labels: bug, component, frontend

#80 Feat/58 payment user db
  server/src/passport.ts
  server/src/repository/category-repository.ts
  server/src/repository/payment-repository.ts
  server/src/repository/transaction-repository.ts
  server/src/routes/__test__/payment-routes.test.ts
  server/src/routes/__test__/transaction-routes.test.ts
  server/src/routes/index.ts
  server/src/routes/payment-routes.ts
  server/src/service/payment-service.ts
  server/src/utils/fetch-wrapper.ts
Labels: api, backend

#85 Feat/63 add transaction component
  README.md
  assets/images/database.png
  client/src/api/category.ts
  client/src/api/transaction.ts
  client/src/components/AddNewTransaction/AddNewTransaction.scss
  client/src/components/AddNewTransaction/AddNewTransaction.test.ts
  client/src/components/AddNewTransaction/AddNewTransaction.ts
  client/src/components/App/App.ts
  client/src/components/BoxInput/BoxInput.scss
  client/src/components/CalendarItem/CalendarItem.scss
  client/src/components/Header/Header.scss
  client/src/components/Header/Header.ts
  client/src/components/ICon/ICon.scss
  client/src/components/SideBar/SideBar.ts
  client/src/components/TransactionList/TransactionList.ts
  client/src/pages/Calendar/Calendar.scss
  client/src/pages/Transaction/Transaction.ts
  client/src/stores/CategoryStore.ts
  client/src/stores/DateStore.ts
  client/src/stores/TransactionStore.ts
  client/src/stores/VisibleStore.ts
  client/src/stores/index.ts
  client/src/utils/Routing.ts
  client/src/utils/getCSVNumber.ts
  client/src/utils/wooact/Component.ts
  client/src/utils/wooact/Diffing.ts
  client/src/utils/wooact/createElement.ts
  client/src/utils/wooact/defaultElements.ts
Labels: component, frontend

#87 Clinet/84 statistics page
  client/src/components/BarChart/BarChart.ts
  client/src/components/LineChart/LineChart.ts
  client/src/components/PieChart/PieChart.scss
  client/src/components/PieChart/PieChart.ts
  client/src/pages/Statistics/Statistics.ts
  client/src/pages/Statistics/bar.html
Labels: frontend

#101 Fit/100 authentication
  client/package.json
  client/src/api/apiRoutes.ts
  client/src/api/payment.ts
  client/src/api/transaction.ts
  client/src/api/user.ts
  client/src/components/AddNewTransaction/AddNewTransaction.ts
  client/src/components/App/App.ts
  client/src/components/Login/Login.ts
  client/src/components/PaymentItem/PaymentItem.ts
  client/src/components/Signup/Signup.ts
  client/src/pages/Payment/Payment.ts
  client/src/pages/SignIn/SignIn.scss
  client/src/pages/SignIn/SignIn.ts
  client/src/stores/PaymentStore.ts
  client/src/utils/fetchWrapper.ts
  server/package.json
  server/src/index.ts
  server/src/middlewares/isAuthenticated.ts
  server/src/passport.ts
  server/src/repository/payment-repository.ts
  server/src/repository/transaction-repository.ts
  server/src/routes/payment-routes.ts
  server/src/routes/transaction-routes.ts
  server/src/service/payment-service.ts
  server/src/service/transaction-service.ts
  server/src/utils/fetch-wrapper.ts
Labels: api, backend, bug, environment, frontend
