Repository woowa-techcamp-2020/hkb-2, pull requests merged in 2020-07, with the labels that each got.

#3 Env/1 client env setup
  client/.gitignore
  client/.prettierrc
  client/babel.config.js
  client/index.html
  client/package-lock.json
  client/package.json
  client/src/index.ts
  client/tsconfig.json
  client/webpack.common.js
  client/webpack.dev.js
  client/webpack.prod.js
  server/package.json
  server/public/index.html
Labels: environment, frontend

#4 github template setup
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: environment

#21 [#11] evn: jest setup
  server/jest.config.js
Labels: environment

#28 Client/14 login component
  client/src/api/apiRoutes.ts
  client/src/api/user.ts
  client/src/components/Header/Header.scss
  client/src/components/Login/Login.ts
  client/src/utils/errorHandler.ts
Labels: frontend

#27 Feat/13 server login api
  server/src/const.ts
  server/src/middlewares/validate-body.ts
  server/src/repository/user-repository.ts
  server/src/routes/__test__/userRoutes.test.ts
  server/src/routes/index.ts
  server/src/routes/userRoutes.ts
  server/src/service/userService.ts
  server/src/utils/db-connection-handler.ts
  server/src/utils/promise-handler.ts
  server/src/utils/query-executor.ts
Labels: api, backend

#31 Feat/30 error handler
  server/src/app.ts
  server/src/errors/CustomError.ts
  server/src/errors/Insufficient-body.ts
  server/src/middlewares/validate-body.ts
  server/src/routes/__test__/userRoutes.test.ts
Labels: backend

#33 Feat/32 connect sign-up api
  client/src/api/apiRoutes.ts
  client/src/api/user.ts
  client/src/components/Login/Login.ts
  server/package-lock.json
  server/package.json
  server/src/app.ts
  server/src/repository/user-repository.ts
Labels: api, backend, feature, frontend

#37 Feat/36 wooact update
  client/src/utils/wooact/Component.ts
  client/src/utils/wooact/Diffing.ts
  client/src/utils/wooact/createElement.ts
  client/src/utils/wooact/eventHandler.ts
Labels: enhancement, feature, frontend

#43 Feat/39 transaction api
  client/src/api/apiRoutes.ts
  client/src/api/transaction.ts
  server/package.json
  server/src/app.ts
  server/src/errors/Insufficient-body.ts
  server/src/errors/custom-error.ts
  server/src/errors/database-error.ts
  server/src/repository/transaction-repository.ts
  server/src/routes/__test__/transaction-routes.test.ts
  server/src/routes/__test__/user-routes.test.ts
  server/src/routes/index.ts
  server/src/routes/transaction-routes.ts
  server/src/routes/user-routes.ts
  server/src/service/transaction-service.ts
  server/src/service/user-service.ts
Labels: api, backend, frontend

#46 Server/45 password hash
  .gitignore
  server/package-lock.json
  server/package.json
  server/src/app.ts
  server/src/passport.ts
  server/src/routes/user-routes.ts
  server/src/service/user-service.ts
Labels: api, backend

#48 Feat/38 transaction page
  client/create-wooact-component.sh
  client/package-lock.json
  client/package.json
  client/src/api/transaction.ts
  client/src/components/App/App.scss
  client/src/components/App/App.ts
  client/src/components/Header/Header.scss
  client/src/components/TransactionItem/TransactionItem.scss
  client/src/components/TransactionItem/TransactionItem.test.ts
  client/src/components/TransactionItem/TransactionItem.ts
  client/src/components/TransactionItem/index.ts
  client/src/components/TransactionList/TransactionList.scss
  client/src/components/TransactionList/TransactionList.test.ts
  client/src/components/TransactionList/TransactionList.ts
  client/src/components/TransactionList/index.ts
  client/src/index.ts
  client/src/styles/_fonts.scss
  client/src/styles/_normalize.scss
  client/src/styles/_variables.scss
  client/src/styles/fonts/Framework7Icons-Regular.eot
  client/src/styles/fonts/Framework7Icons-Regular.ttf
  client/src/styles/fonts/Framework7Icons-Regular.woff
  client/src/styles/fonts/Framework7Icons-Regular.woff2
  client/src/styles/fonts/noto-sans-kr/noto-sans-kr-v12-latin-regular.eot
  client/src/styles/fonts/noto-sans-kr/noto-sans-kr-v12-latin-regular.svg
  client/src/styles/fonts/noto-sans-kr/noto-sans-kr-v12-latin-regular.woff
  client/src/styles/fonts/noto-sans-kr/noto-sans-kr-v12-latin-regular.woff2
  client/src/utils/getCSVNumber.ts
  client/src/utils/wooact/Component.ts
  client/src/utils/wooact/Diffing.ts
  client/webpack.common.js
  server/public/index.html
  server/src/repository/transaction-repository.ts
  server/src/routes/user-routes.ts
  server/src/service/user-service.ts
Labels: frontend
